### ISSUE TITLE
TTS Announce?

### ISSUE THREAD

**Issue by nhadler** [onlyoneme/home-assistant-custom-components-wiim#16]
Does this integration support the tts announce feature? Whenever I announce with it, it doesn't resume playing the media from before.

Here's an example of the service I called: 

```yaml
service: media_player.play_media
target:
  entity_id: media_player.apartment_speakers_wiim
data:
  media_content_id: >-
    media-source://tts/google_translate?message=Hi+there+it+looks+like+we+have+a+visitor+at+our+frontdoor
  media_content_type: provider
  announce: true
```

It plays the announcement fine, but fails to resume the music. I see that the original linkplay integration claims to support the feature.
