### ISSUE TITLE
Multiroom support

### ISSUE THREAD

**Issue by ZeroZXD** [onlyoneme/home-assistant-custom-components-wiim#6]
Hello, 

Would it be possile to add multiroom support to this like the linkplay Home Assitant integration?

**Comment by mitrokun** [comment]
As a temporary solution, you can use the Rest API ( https://www.home-assistant.io/integrations/rest )

Here is my example of using to connect and disconnect WiiM to the master (up2stream)
```
wiim2main:
  url: 'https://192.168.1.72/httpapi.asp?command=ConnectMasterAp:JoinGroupMaster:eth192.168.1.219:wifi0.0.0.0'
  verify_ssl: false
wiimoutmain:
  url: 'http://192.168.1.219/httpapi.asp?command=multiroom:SlaveKickout:192.168.1.72'
  verify_ssl: false

```

But you can use any other commands from the official API, including on the arilyc website.
