### ISSUE TITLE
how more than 1 wiim player in home assistant

### ISSUE THREAD

**Issue by p8ulus** [onlyoneme/home-assistant-custom-components-wiim#9]
how can i insert 3 wiim players into home assistant yaml code. Currently I have 1 wiim player in yaml code that I can see and control from home assistant. When I insert second in yaml code I get error, twice uuid, name, volume_step.

    - platform: wiim_custom
      host: 192.168.1.xx
      name: xxxxxx
      uuid: 'xxxxxxxxxxxxxxxxxxxxx'
      volume_step: 10

    - platform: wiim_custom
      host: 192.168.1.xx
      name: xxxxxx
      uuid: 'xxxxxxxxxxxxxxxxxxxxx'
      volume_step: 10

**Comment by onlyoneme** [comment]
Like below:

```
media_player:
    - platform: wiim_custom
      host: 192.168.0.1
      name: WiiM Mini
      uuid: xxxxxxxxxxxxxxxxxxxxx
    - platform: wiim_custom
      host: 192.168.0.2
      name: WiiM Pro 2
      uuid: xxxxxxxxxxxxxxxxxxxxx
    - platform: wiim_custom
      host: 192.168.0.3
      name: WiiM Pro 1
      uuid: xxxxxxxxxxxxxxxxxxxxx
```
